using System.Runtime.Serialization;

namespace Blazorise.ChartsEx
{
  /// <summary>
  /// The minorTick configuration is nested under the ticks configuration in the minor key. It defines options for the minor tick marks that are generated by the axis. Omitted options are inherited from ticks configuration.
  /// </summary>
  [DataContract]
  public class AxisMinorTick
  {
    /// <summary>
    /// Font color for tick labels.
    /// </summary>
    [DataMember]
    public string FontColor { get; set; } = "#666";

    /// <summary>
    /// Font family for the tick labels, follows CSS font-family options.
    /// </summary>
    [DataMember]
    public string FontFamily { get; set; } = "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif";

    /// <summary>
    /// Font size for the tick labels.
    /// </summary>
    [DataMember]
    public int FontSize { get; set; } = 12;

    /// <summary>
    /// Font style for the tick labels, follows CSS font-style options (i.e. normal, italic, oblique, initial, inherit).
    /// </summary>
    [DataMember]
    public string FontStyle { get; set; } = "normal";

    /// <summary>
    /// Height of an individual line of text.
    /// </summary>
    [DataMember]
    public decimal LineHeight { get; set; } = 1.2m;
  }
}
