using System.Runtime.Serialization;

namespace Blazorise.ChartsEx
{
  /// <summary>
  /// The majorTick configuration is nested under the ticks configuration in the major key. It defines options for the major tick marks that are generated by the axis. Omitted options are inherited from ticks configuration. These options are disabled by default.
  /// </summary>
  [DataContract]
  public class AxisMajorTick
  {
    /// <summary>
    /// If true, major tick options are used to show major ticks.
    /// </summary>
    [DataMember]
    public bool Enabled { get; set; }

    /// <summary>
    /// Font color for tick labels.
    /// </summary>
    [DataMember]
    public string FontColor { get; set; } = "#666";

    /// <summary>
    /// Font family for the tick labels, follows CSS font-family options.
    /// </summary>
    [DataMember]
    public string FontFamily { get; set; } = "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif";

    /// <summary>
    /// Font size for the tick labels.
    /// </summary>
    [DataMember]
    public int FontSize { get; set; } = 12;

    /// <summary>
    /// Font style for the tick labels, follows CSS font-style options (i.e. normal, italic, oblique, initial, inherit).
    /// </summary>
    [DataMember]
    public string FontStyle { get; set; } = "normal";

    /// <summary>
    /// Height of an individual line of text.
    /// </summary>
    [DataMember]
    public decimal LineHeight { get; set; } = 1.2m;
  }
}
